default:
  type: node
  screens:
  - name: index
    backgroundImage: true
    regions:
    - type: row
      size: fixed
      components:
      - PageNav
    - type: row
      scrollable: true
      components:
      - PageHeaderImage
      - BodyText
      - ChildNodes
